<a href="https://colab.research.google.com/github/404S-retr0/Even_Dead_I_Am-_The_Hero-E.D.I.T.H-/blob/main/friday_lang_detect.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import string
import re
import codecs
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import feature_extraction
from sklearn import linear_model 
from sklearn import pipeline 
from sklearn import metrics
from sklearn.model_selection import train_test_split
!wget https://raw.githubusercontent.com/404S-retr0/Even_Dead_I_Am-_The_Hero-E.D.I.T.H-/main/english_us_wordlist_top_100k.txt
!wget https://raw.githubusercontent.com/404S-retr0/Even_Dead_I_Am-_The_Hero-E.D.I.T.H-/main/czech_wordlist_top_100k_2016_02_11.txt
!wget https://raw.githubusercontent.com/404S-retr0/Even_Dead_I_Am-_The_Hero-E.D.I.T.H-/main/croatian_wordlist_top_100k.txt
!wget https://raw.githubusercontent.com/404S-retr0/Even_Dead_I_Am-_The_Hero-E.D.I.T.H-/main/dutch_wordlist_top_100k_2012_05.txt
!wget https://raw.githubusercontent.com/404S-retr0/Even_Dead_I_Am-_The_Hero-E.D.I.T.H-/main/danish_wordlist_top_100k_2011_12.txt
eng_df = pd.read_csv("english_us_wordlist_top_100k.txt","utf-8",header=None,names=["English"]) 
eng_df
cro_df = pd.read_csv("croatian_wordlist_top_100k.txt","utf-8",header=None,names=["Croatian"]) 
cro_df
cze_df = pd.read_csv("czech_wordlist_top_100k_2016_02_11.txt","utf-8",header=None,names=["Czech"]) 
cze_df
dan_df = pd.read_csv("danish_wordlist_top_100k_2011_12.txt","utf-8",header=None,names=["Danish"]) 
dan_df
dut_df = pd.read_csv("dutch_wordlist_top_100k_2012_05.txt","utf-8",header=None,names=["Dutch"]) 
dut_df

--2021-01-23 18:04:24--  https://raw.githubusercontent.com/404S-retr0/Even_Dead_I_Am-_The_Hero-E.D.I.T.H-/main/english_us_wordlist_top_100k.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3055574 (2.9M) [text/plain]
Saving to: ‘english_us_wordlist_top_100k.txt’

english_us_wordlist 100%[===================>]   2.91M  --.-KB/s    in 0.1s    

2021-01-23 18:04:24 (25.2 MB/s) - ‘english_us_wordlist_top_100k.txt’ saved [3055574/3055574]

--2021-01-23 18:04:24--  https://raw.githubusercontent.com/404S-retr0/Even_Dead_I_Am-_The_Hero-E.D.I.T.H-/main/czech_wordlist_top_100k_2016_02_11.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:18: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:24: ParserWarning: Falling 

Dutch
0                                  ��1\tde
1                                            
2                                 2\thet
3                                            
4                                 3\teen
...                                        ...
199996  99999\tonbekommerde
199997                                       
199998  100000\topgeschuurd
199999                                       
200000                                       

[200001 rows x 1 columns]

In [ ]:
for char in string.punctuation:
  print(char,end=" ")
translate_table = dict ((ord(char),None) for char in string.punctuation)

! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~ 

In [ ]:
data_eng = []
lang_eng = []
for i,line in eng_df.iterrows():
  line = line['English']
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+","",line)
    line = line.translate(translate_table)
    data_eng.append(line)
    lang_eng.append("English")

In [ ]:
data_cro = []
lang_cro = []
for i,line in cro_df.iterrows():
  line = line['Croatian']
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+","",line)
    line = line.translate(translate_table)
    data_cro.append(line)
    lang_cro.append("Croatian")

In [ ]:
data_cze = []
lang_cze = []
for i,line in cze_df.iterrows():
  line = line['Czech']
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+","",line)
    line = line.translate(translate_table)
    data_cze.append(line)
    lang_cze.append("Czech")

In [ ]:
data_dan = []
lang_dan = []
for i,line in dan_df.iterrows():
  line = line['Danish']
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+","",line)
    line = line.translate(translate_table)
    data_dan.append(line)
    lang_dan.append("Danish")

In [ ]:
data_dut = []
lang_dut = []
for i,line in dut_df.iterrows():
  line = line['Dutch']
  if len(line) !=0:
    line = line.lower()
    line = re.sub(r"\d+","",line)
    line = line.translate(translate_table)
    data_dut.append(line)
    lang_dut.append("Dutch")

In [ ]:
df=pd.DataFrame({"Text":data_eng+data_cro+data_cze+data_dan+data_dut,
                 "Language":lang_eng+lang_cro+lang_cze+lang_dan+lang_dut})
print(df.shape)
df

(1015528, 2)


Text Language
0                    ��rank\tword  English
1                                          English
2                              \tthe  English
3                                          English
4                                \tto  English
...                                    ...      ...
1015523  \tonbekommerde    Dutch
1015524                                      Dutch
1015525   \topgeschuurd    Dutch
1015526                                      Dutch
1015527                                      Dutch

[1015528 rows x 2 columns]

In [ ]:
x,y=df.iloc[:,0],df.iloc[:,1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(812422,)
(203106,)
(812422,)
(203106,)


In [ ]:
vectorizer = feature_extraction.text.TfidfVectorizer(ngram_range=(1,3),analyzer='char')
pipe_lr_r13 = pipeline.Pipeline([
                                 ('vectorizer',vectorizer),
                                 ('clf',linear_model.LogisticRegression(n_jobs=-1))
])

In [ ]:
pipe_lr_r13.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 2), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_sc

In [ ]:
y_predicted = pipe_lr_r13.predict(x_test)

In [ ]:
acc = (metrics.accuracy_score(y_test,y_predicted))*100
print(acc,'%')

37.03189467568659 %


In [ ]:
matrix = metrics.confusion_matrix(y_test,y_predicted)
print('confusion matrix : \n',matrix)

confusion matrix : 
 [[15215   746 20957  2033  2659]
 [ 4305 12280 21241  1125  2634]
 [ 1815  1058 29934  3727  3718]
 [ 3138   585 23579  7785  4744]
 [ 2648   702 22914  3564 10000]]


In [ ]:
import pickle
lrFile = open('LRModel.pckl','wb')
pickle.dump(pipe_lr_r13,lrFile)
lrFile.close()

In [ ]:
def lang_detect(text):
  import numpy as np
  import string
  import re
  import pickle
  translate_table = dict ((ord(char),None) for char in string.punctuation)

  global lrLangDetectModel
  lrLangDetectFile = open('LRModel.pckl','rb')
  lrLangDetectModel = pickle.load(lrLangDetectFile)
  lrLangDetectFile.close();

  text = " ".join(text.split())
  text = text.lower()
  text = re.sub(r"\d","",text)
  text = text.translate(translate_table)
  pred = lrLangDetectModel.predict([text])
  prob = lrLangDetectModel.predict_proba([text])
  return pred[0]

In [ ]:
lang_detect("hello i just built my own language detection model")

'Dutch'

In [ ]:
lang_detect("vi")

'Dutch'